apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cdtest-delivery-pipeline
description: main application pipeline
serialPipeline:
  stages:
    - targetId: run-cdtest-dev
      profiles: [dev]
    - targetId: run-cdtest-prod
      profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-cdtest-dev
description: Cloud Run development service
run:
  location: projects/PROJECT_ID/locations/asia-northeast1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-cdtest-prod
description: Cloud Run production service
run:
  location: projects/PROJECT_ID/locations/asia-northeast1